require_relative './parsers/base'
require_relative './parsers/remote_co'
require_relative './parsers/flex_jobs'
require_relative './parsers/js_remotely'
require_relative './parsers/rust_jobs'
require_relative './parsers/just_remote_co'
require_relative './parsers/builtin'
require_relative './parsers/indeed'
require_relative './parsers/rss'

